name: quiz_app_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver: ^2.0.3
  share: ^2.0.4
  path_provider: ^2.0.2
  url_launcher: ^6.0.6
  share_plus: ^3.0.0
  # flutter_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
